#Server Makefile
#Author: David Baas


packet_server.o: packet_server.cpp
	clang++ -c packet_server.cpp

file_util.o: file_util.cpp
	clang++ -c file_util.cpp

test.o: test.cpp
	clang++ -c test.cpp

socket.o: socket.cpp
	clang++ -c socket.cpp

ftp_server.o: ftp_server.cpp
	clang++ -c ftp_server.cpp
